-- How to read raw data from a stream?

import System.File
import Data.Buffer

-- Read chunks from a File into a list of lists of bits8.
-- Generated by CoPilot to demonstrate how to read bytes
-- in chunks from a 'File', but note that not all
-- 'IO streams' share the same API as they do in e.g. Java.
-- There is a separate API for reading from network sockets,
-- and if you want a unified API, you're on your own to build that.
readChunks : File -> Int -> IO (Either FileError (List (List Bits8)))
readChunks fn chunkSize = do
	Just buf <- newBuffer chunkSize
		| Nothing => pure (Left FileReadError)
	go buf
	where
		go : Buffer -> IO (Either FileError (List (List Bits8)))
		go buf = do
			result <- readBufferData fn buf 0 chunkSize
			case result of
				Left err => pure (Left err)
				Right 0 => pure (Right [])
				Right n => do
					bytes <- traverse (getBits8 buf) [0 .. n-1]
					rest <- go buf
					pure $ (bytes ::) <$> rest
