#+TITLE: Scratch38.1 Block File Format

A relatively efficient format for storing Minecraft map data
(i.e. spans of 4kb blocks).

** Original notes

From [[http://wherever-files.nuke24.net/uri-res/raw/urn:bitprint:KCABIKZALTFCIWSCJTVBTCNRI7FRYXLT.N7JPWPAAU43Q2ZWWVJLKFPNN7EOUZ3YG3MTYS3Y/S38S1-original-README.org][S0001/README.org]], last modified 2023-0905T13:34.
Not sure why this was separate;
maybe just started on a different computer before I
made this Git repo for it.

#+begin_quote
#+TITLE: urn:oid:1.3.6.1.4.1.44868.261.38.1

File format for relatively efficient storing
of Minecraft map data (i.e. spans of 4kb blocks)

Initial thoughts:
- By default 'just a bunch of raw data, which you're more likely
  to make sense of if it's chunked into 4kiB pieces'
- Files must always be a multiple of 4kiB in length
- Files can be concatenated together, and the result is
  equivalent to the two original files
  - Implication: No by-absolute-offset referencess between
    chunks within the file
- Blocks with a special pattern at the beginning of the 4kiB
  can have special meaning, useful for providing chunks
  of data that aren't simply 4kiB chunks of arbitrary data,
  for example:
  - a bunch of tigertree nodes
  - [[http://www.nuke24.net/docs/2003/draft-jchapweske-thex-02.html][THEX data]]
  - Properties file-style dictionary
#+end_quote

** Basic idea

Length-prefixed blocks which *happen* to be on 4kiB boundaries most of the time.
When not storing 4kiB chunks, feel free to use anything else, on the condition that
(a) file is always a multiple of 4 kiB long,
(b) the first block in the file starts on a 4 kiB boundary.

This way, one of these files can always be processed by skipping
through 4kiB at a time until a block header is found.
After that, arbitrarily-sized blocks can be processed in order.

** Other possibilities

Note that this could all be accomplished with something like
https://en.wikipedia.org/wiki/Resource_Interchange_File_Format,
using padding chunks to line things up.

Even better would be if an existing container format,
such as zip, allows splitting data into chunks.
Then these block files could be readable by any old Joe,
and thereby useful for much more than just special-purpose
block storage.

*** Zip

Q: Can I just ~cat some stuff zip-file.zip~ and have a valid zip file?

A: According to ~zip~ on my Linux computer, yes.
Though it may complain a little bit about junk at the beginning of the file.

Q: Can I just ~cat some stuff jar-file.jar~ and Java will still accept and run it?

A: According to that same Linux machine, yes.
   And according to OpenJDK 11.0.14.1 and Semuru Java 17.0.5.0, also yes.

** Format

Any number of 4 kiB chunks that do not start with "#S38.1:BLOCK" are ignored.
This way arbitrary file formats (e.g. a RIFF file or a PNG or whatever)
can be combined with S38.1 block files.

Once a block appears in a stream, other alignment can be used, e.g. 1kiB,
or none at all.  To stay on 'nice fixed sized chunk' boundaries,
blocks must have lengths that are multiples of that chunk size, e.g. 4kiB
(this is why block size is independent of payload offset/length).

#+BEGIN_SRC
block = block-header block-metadata payload padding

block-header = "#S38.1:BLOCK:" block-length ("," payload-offset "," payload-length)? (" " tag)?  newline

block-metadata = metadata-header* + (newline + padding)?

metadata-header = metadata-header-key ": " " "* metadata-header-value newline
#+END_SRC

- ~payload-offset~ :: the offset, in bytes, from the beginning of the block (the "#s38.1:block:")
  to the beginning of the payload
- ~payload-length~ :: length, in bytes, of the payload.
- ~tag~ is an arbitrary string, maybe a URL or the payload's MIME type,
  that can be used to provide simple metadata about the data stored in the block.
- Meaning of ~padding~ is unspecified.  Could be zeroed out,
  filled with random data, or contain hidden messages hinted-at by headers,
  and if large enough may even contain more blocks!
  Though that woulkd probably be silly.

Notes:
- Numbers are decimal-encoded.
- ~payload-offset + payload-length <= block-length~, or the block can be considered malformed.
- For simplicity, the TEF metadata format is slightly stricter than regular TEF.
  Each header is a single line.
- "#" followed by anything other than space, newline, or exclamation point is reserved
- ~block-metadata~ can be ignored, as it is basically padding,
  just in a standard format (which itself contains padding!)
- ~header-content-type~ and ~header-content-length~ headers, if present,
  refer to any data that appears directly after the blank
  line after the headers, not to the block payload.

Example:

#+BEGIN_SRC
#S38.1:BLOCK:16384,4096,12288 application/x-chunks:4096
# x-chunks:<size> being a hypothetical format that is simply
# a series of chunks of the given length.
# The following text resides between the "#S38.1" header line
# and the content
header-content-type: text/plain
# Since the block metadata section is implicitly
# 'everything up until the payload', to avoid having
# junk in the metadata content, either pad the beginning
# with comment lines, or use header-content-length to specify
# exactly how many bytes of content there are.
# Between the end of the metadata content and the payload, then,
# would be yet another secret space...
header-content-length: 129

Here is some text!  This could just be filler,
or it could be machine-readable metadata about the block.
Do with it as you will.
#+END_SRC

** Idea for a 'chunk list' dialect

Note: This idea is, while 100% compatible with the framing
specified above, silly and redundant, as the blocks themselves
are already capable of representing whatever I need.

For this dialect, payload offset/length are redundant
so can/should be left out of the block header.

A list of chunks is stored in the block metadata section:

#+BEGIN_SRC
#S38.1:BLOCK:<total length of block, including this line>
# Any TEF-style headers go here
whatever-metadata-for-the-block: whatever value
header-content-type: application/x-scratch38.1-chunklist
header-content-length: <length of chunk list>
# Empty line indicates end of headers

# The chunklist is a series of lines,
# where each line gives an item count, an item length, and 'flags',
# which can be used to hint at the interpretation of the content
1 <length of header> block-header
1 <length of padding before first chunk> padding
# More lines of the format: <count> <length> [<flags>]
1 <remainder of chunk> padding
#+END_SRC

~padding~ chunks are garbage and can be overwritten to
cram more data in, if desired.
